# Creating Array

In [3]:
import numpy as np
arr=np.array([2,4,5,6])
print(arr)
arr

[2 4 5 6]


array([2, 4, 5, 6])

# What is array
A one dimensional array look like a list

# Restrictions of NumPy array
All elements of the array must be of the same type of data.
Once created, the total size of the array can’t change.


In [6]:
import numpy as neha
arr=neha.array([122,45,"hey"])
arr
# type(arr)

array(['122', '45', 'hey'], dtype='<U21')

In [7]:
arr[0]

np.str_('122')

In [8]:
arr[-1]

np.str_('hey')

In [9]:
a=np.array([90,34,56,78])
a[0:2]

array([90, 34])

In [10]:
a=np.array([34,67,89,000])
a.pop(1)

AttributeError: 'numpy.ndarray' object has no attribute 'pop'

# 0-D Array


In [11]:
arr=np.array(43)
arr

array(43)

In [12]:
type(arr)

numpy.ndarray

# 1-D Array

In [13]:
arr=np.array([3,7,8,9])
arr

array([3, 7, 8, 9])

In [14]:
type(arr)

numpy.ndarray

# 2-D Array

In [15]:
arr=np.array([[6,7,9,0],
              [7,8,9,6],
              [7,6,5,3],
              [6,4,9,7]
             ])
arr

array([[6, 7, 9, 0],
       [7, 8, 9, 6],
       [7, 6, 5, 3],
       [6, 4, 9, 7]])

In [16]:
type(arr)

numpy.ndarray

In [19]:
arr[0]=9
print(arr)

[[9 9 9 9]
 [7 8 9 6]
 [7 6 5 3]
 [6 4 9 7]]


In [21]:
arr[0:4]

array([[9, 9, 9, 9],
       [7, 8, 9, 6],
       [7, 6, 5, 3],
       [6, 4, 9, 7]])

***Another difference between an array and a list of lists is thar an element of the array can be accessed by spacifying the index along each axis within a singnal set of square brackets , separated by Commas***

In [3]:
import numpy as np
arr=np.array(78)
arr.ndim

0

In [19]:
one_d_arr=np.array([34,4,5,5,8,6])
one_d_arr.ndim
one_d_arr.dtype

dtype('int64')

In [16]:
two_d_arr=np.array([[45,67,88,55],
        [45,6,7,9],
        [45,6,78,9],
        [3,5,6,8]
             ])
two_d_arr.ndim
two_d_arr.dtype

dtype('int64')

In [9]:
one_d_arr.size

4

In [10]:
two_d_arr.size

16

In [11]:
two_d_arr.shape

(4, 4)

In [12]:
one_d_arr.shape

(4,)

***Shape: The shape of an array is a tuple of an non-negative integers that specify the number of elements along each dimension***

***size: The data type of the element of the array can be checked using the dtype attribute***

In [14]:
one_d_arr.dtype

dtype('int64')

In [20]:
two_d_arr.dtype

dtype('int64')

# Some other Techniques to Create an array

***The section covers np.zeros() np.ones() np.empty np.arrange np.linspace***

In [23]:
zero_arr=np.zeros(8)
zero_arr

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
one_arr=np.ones(4)
one_arr

array([1., 1., 1., 1.])

In [25]:
empty_arr=np.empty(4)
empty_arr

array([1., 1., 1., 1.])

In [43]:
x=np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [41]:
empty_arr.shape

(4, 2)

In [32]:
zero_arr=np.zeros((8,7))
zero_arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [38]:
empty_arr=np.empty((4,2))
empty_arr.size
empty_arr.shape
empty_arr

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [53]:
x=np.arange(1,10,2)# (start,stop,step)
# x.shape
# x.size
x

array([1, 3, 5, 7, 9])

In [55]:
x=np.linspace(1,100,44)#(start,stop,num)
# x.shape
# x.size
x

array([  1.        ,   3.30232558,   5.60465116,   7.90697674,
        10.20930233,  12.51162791,  14.81395349,  17.11627907,
        19.41860465,  21.72093023,  24.02325581,  26.3255814 ,
        28.62790698,  30.93023256,  33.23255814,  35.53488372,
        37.8372093 ,  40.13953488,  42.44186047,  44.74418605,
        47.04651163,  49.34883721,  51.65116279,  53.95348837,
        56.25581395,  58.55813953,  60.86046512,  63.1627907 ,
        65.46511628,  67.76744186,  70.06976744,  72.37209302,
        74.6744186 ,  76.97674419,  79.27906977,  81.58139535,
        83.88372093,  86.18604651,  88.48837209,  90.79069767,
        93.09302326,  95.39534884,  97.69767442, 100.        ])

## Concatenate & Shorting of Arrays

In [59]:
a=np.array([3,5,6,7,8])
a_shorted=np.sort(a)
a_shorted

array([3, 5, 6, 7, 8])

## np.sort()

In [64]:
a_shorted.ndim

1

In [65]:
a_shorted.shape

(5,)

In [61]:
b=np.array([[3,51,6,8],
            [4,5,7,8],
            [4,5,61,7],
            [4,15,7,8]
           ])
b_shorted=np.sort(b)
b_shorted

array([[ 3,  6,  8, 51],
       [ 4,  5,  7,  8],
       [ 4,  5,  7, 61],
       [ 4,  7,  8, 15]])

In [62]:
b_shorted.size

16

In [63]:
b_shorted.shape

(4, 4)

## np.concatenate()

In [66]:
x=np.array([[3,2,7,9],
            [3,5,7,8],
            [7,4,4,3]
           ])
y=np.array([[3,2,1,5],
            [4,3,5,6],
            [4,2,4,5]
           ])
np.concatenate((x,y))

array([[3, 2, 7, 9],
       [3, 5, 7, 8],
       [7, 4, 4, 3],
       [3, 2, 1, 5],
       [4, 3, 5, 6],
       [4, 2, 4, 5]])

In [69]:
x.size

12

In [70]:
y.size

12

In [71]:
x.shape

(3, 4)

In [72]:
y.shape

(3, 4)

axis = 0(Rows ke hisaab se jodna,Vertically (neeche))
|
|
|
|
|


axis =1 (Columns ke hisaab se jodna,Horizontally (side me))
_________________________>

In [14]:
import numpy as np
a=np.array([[2,4,5,7],
          [3,5,7,8]
           ])
b=np.array([[3,4,7,9],
          [3,4,6,8]
           ])
np.concatenate((a,b),axis=1)

array([[2, 4, 5, 7, 3, 4, 7, 9],
       [3, 5, 7, 8, 3, 4, 6, 8]])

In [15]:
import numpy as np
a=np.array([[2,4,5,7],
          [3,5,7,8]
           ])
b=np.array([[3,4,7,9],
          [3,4,6,8]
           ])
np.concatenate((a,b),axis=0)


array([[2, 4, 5, 7],
       [3, 5, 7, 8],
       [3, 4, 7, 9],
       [3, 4, 6, 8]])

In [18]:

One_D_Array=np.array([12, 5, 9, 20, 1])
short=np.sort(One_D_Array)
print(short)

[ 1  5  9 12 20]


In [19]:
arr1_d=np.array([15, 3, 9, 12, 6])
element_2=np.sort(arr1_d)
second_largest=element_2[-2]
print(second_largest)

12


In [21]:
sort_array=np.array([[3, 1, 2],
                      [9, 7, 8]
                    ])
sorted_array=np.sort(sort_array)
sorted_array


array([[1, 2, 3],
       [7, 8, 9]])

In [23]:
collage_student=np.ones((10,20))
collage_student

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [24]:
collage_student=np.ones((20,10))
collage_student

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
collage_student.ndim

2

In [26]:
collage_student.size

200

In [27]:
collage_student.shape

(20, 10)

In [28]:
collage_student.sort

<function ndarray.sort>

In [29]:
collage_student=np.ones((20,10))
collage_student_=np.sort(collage_student)
collage_student_

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [30]:
student=np.zeros((17,9))
student

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
student=np.arange(1,200,9)
student

array([  1,  10,  19,  28,  37,  46,  55,  64,  73,  82,  91, 100, 109,
       118, 127, 136, 145, 154, 163, 172, 181, 190, 199])

In [35]:
student=np.linspace(1,200,9)
student

array([  1.   ,  25.875,  50.75 ,  75.625, 100.5  , 125.375, 150.25 ,
       175.125, 200.   ])

# Reshaping in array

***arr.shape***

***Using arr.reshape() will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.***

In [2]:
import numpy as np


In [4]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [5]:
b=a.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
c=b.reshape(4,1)

In [9]:
c=b.reshape(6,1)
c

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [10]:
a=a.reshape(1,6)
a

array([[0, 1, 2, 3, 4, 5]])

In [11]:
a=a.reshape(6,1)
a

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

# Indexing using conditional in Arrays 

In [13]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a
a>5


array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [16]:
list1=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]
print([list1 < 5])

TypeError: '<' not supported between instances of 'list' and 'int'

In [14]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a
a<5


array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [15]:

print([a%2==0])


[array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])]


In [19]:
c=c[(a>2)or (a<11)]
c=c[(a>2)and (a<11)]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [22]:
c=c[(a>2)& (a<11)]
print(c)

IndexError: boolean index did not match indexed array along axis 0; size of axis is 6 but size of corresponding boolean axis is 3

In [23]:
d=a[(a>5) | (a==5)]
d

array([ 5,  6,  7,  8,  9, 10, 11, 12])

# Basic Opretion Arrays 

In [35]:
DATA=np.array([9,3,6,7])
DATA1=np.array([2,4,7,8])
print(DATA+DATA1)# addition

[11  7 13 15]


In [34]:
print(DATA-DATA1)# subtract

[ 7 -1 -1 -1]


In [33]:
print(DATA*DATA1)# multiplication

[18 12 42 56]


In [32]:
print(DATA/DATA1)# division

[4.5        0.75       0.85714286 0.875     ]


In [28]:
lst=np.array([3,6,7,8])
lst.sum

<function ndarray.sum>

In [29]:
lst=np.array([3,6,7,8])
lst.sum()

np.int64(24)

In [31]:
b=np.array([[1,1],
            [2,2]
           ])
b.sum(axis=0)
            

array([3, 3])

In [36]:
b.sum(axis=1)

array([2, 4])

# Brodcasting

***Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes***

***There are many broadcasting rules, which you can learn from the numpy documentation***

In [52]:
distance_in_km=np.array([2,4,6,8])
single_value=np.array(1000)
distance_in_km *  single_value

array([2000, 4000, 6000, 8000])

In [50]:
print(single_value.shape)

()


In [49]:
print(single_value.size)

1


In [48]:
print(distance_in_km.shape)

(4,)


In [47]:
print(distance_in_km.size)

4


In [45]:
print(distance_in_km.ndim)

1


In [46]:
print(single_value.ndim)

0


In [3]:
import numpy as np
highest_marks=np.array([300,400,340,234,23])
added_marks=np.array(50)
highest_marks + added_marks

array([350, 450, 390, 284,  73])

In [4]:
added_marks.size

1

In [5]:
added_marks.shape

()

In [6]:
added_marks.ndim

0

In [7]:
highest_marks.size

5

In [8]:
highest_marks.shape

(5,)

In [9]:
highest_marks.ndim

1

In [10]:
sum0=np.array([12,3,567,7])
sum1=np.array([3,5,6,7])
sum0+sum1

array([ 15,   8, 573,  14])

In [13]:
sum0=np.array([12,3,567,7])
sum0.sum()

np.int64(589)

In [19]:
sum0=np.array([12,3,567,7])
shorted=np.sort(sum0)
shorted

array([  3,   7,  12, 567])

In [23]:
sum0=np.array([12,3,567,7])
shorted=np.sort(sum0[::-1])
shorted

array([  3,   7,  12, 567])

In [1]:
import numpy as np
slicing_arr=np.array([92,32,44,64,74])
print(slicing_arr[0])
print(slicing_arr[::-1])
print(slicing_arr[0:4])
print(slicing_arr[1:2])
print(slicing_arr.size)
print(slicing_arr.shape)
print(slicing_arr.ndim)
print(slicing_arr.astype(str))
print(slicing_arr.astype(float))

92
[74 64 44 32 92]
[92 32 44 64]
[32]
5
(5,)
1
['92' '32' '44' '64' '74']
[92. 32. 44. 64. 74.]


# Fancy Indexing

In [2]:
fancy_indexing=np.array(["neha","nikita","sona","sagrika"])
print(fancy_indexing[[0,2]])
print(fancy_indexing.shape)
print(fancy_indexing.size)
print(fancy_indexing.ndim)


['neha' 'sona']
(4,)
4
1


# Reshaping and manipulating

***.ravel()-> view***

***.flatten()-> copy***

In [3]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d.ravel())
print(arr_2d.flatten())

[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]


# Insert 

In [4]:
arr=np.array([12,35,55,33,78,99])
print(arr)
new_arr=np.insert(arr,2,100,axis=0)
print(new_arr)

[12 35 55 33 78 99]
[ 12  35 100  55  33  78  99]
